import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { profile, projects, publications, experience, education, skills, certifications, workshops } from '../src/content.mjs';
import { field, projectVisual } from '../src/visuals.mjs';
import { canonicalUrl, googleSiteVerification, identityData, sitemapXml } from '../src/seo.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const arrow = '<span class="arrow" aria-hidden="true">↗</span>';
const forward = '<span class="arrow" aria-hidden="true">→</span>';
const tags = values => `<div class="tags">${values.map(value=>`<span class="tag">${esc(value)}</span>`).join('')}</div>`;
const external = (url, label, cls = 'text-link') => `<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label}${arrow}</a>`;
const resumeRequestHref = `mailto:${profile.email}?subject=${encodeURIComponent('Resume request')}&body=${encodeURIComponent('Hi Shanmukha,\r\n\r\nI would like to request your latest Resume.\r\n\r\nName:\r\nOrganization:\r\nOpportunity or reason for request:\r\n\r\nThank you.')}`;
const resume = () => `<a class="text-link" href="${esc(resumeRequestHref)}" data-resume-request="true">Request Resume ${arrow}</a>`;
const eyebrow = text => `<div class="eyebrow">${text}</div>`;
const navItems = [['Home','index.html'],['About','about.html'],['Experience','experience.html'],['Projects','projects.html'],['Research','research.html'],['Contact','contact.html']];

function layout({title,description,active,content,prefix='',file='index.html',cta=true}) {
  const canonical = canonicalUrl(file);
  const pageTitle = file === 'index.html' ? `${profile.fullName} | Machine Learning & Research` : `${title} · ${profile.fullName}`;
  const indexing = file === '404.html' ? 'noindex, follow' : 'index, follow, max-image-preview:large';
  const verification = file === 'index.html' ? `<meta name="google-site-verification" content="${esc(googleSiteVerification)}">` : '';
  const structuredData = file === '404.html' ? '' : `<script type="application/ld+json">${JSON.stringify(identityData({file,title:pageTitle,description})).replace(/</g, '\\u003c')}</script>`;
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f8f7f3"><title>${esc(pageTitle)}</title><meta name="description" content="${esc(description)}"><meta name="author" content="${esc(profile.fullName)}">${verification}<meta name="robots" content="${indexing}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(pageTitle)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}">${structuredData}<link rel="sitemap" type="application/xml" href="${prefix}sitemap.xml"><link rel="icon" href="${prefix}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}assets/styles.css"><script src="${prefix}assets/site.js" defer></script><noscript><style>.menu-toggle,.filters,.copy-button{display:none}@media(max-width:860px){.site-header{height:auto}.header-inner{flex-wrap:wrap;gap:12px;padding-block:18px}.site-nav{display:flex;position:static;flex-wrap:wrap;gap:8px 16px;padding:0;box-shadow:none;border:0}.site-nav a{padding:6px}.site-nav a[aria-current]:after{display:none}.site-nav .nav-contact{margin:0;padding:6px 12px}}</style></noscript></head>
<body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container header-inner"><a class="brand" href="${prefix}index.html" aria-label="Shanmukha Krishna Chaitanya Munagala, home"><img class="brand-mark" src="${prefix}assets/favicon.svg" width="35" height="35" alt=""><span>Shanmukha Krishna Chaitanya Munagala<small>Machine Learning & Research</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="site-nav">Menu <span aria-hidden="true">☰</span></button><nav class="site-nav" id="site-nav" aria-label="Main navigation">${navItems.map(([name,url])=>`<a href="${prefix}${url}"${active===name?' aria-current="page"':''}${name==='Contact'?' class="nav-contact"':''}>${name}${name==='Contact'?' <span aria-hidden="true">↗</span>':''}</a>`).join('')}</nav></div></header>
<main id="main" class="container">${content}${cta?`<section class="bottom-cta" aria-labelledby="cta-title"><div><h2 id="cta-title">Good work starts with a conversation.</h2><p>Machine learning, research, or an interesting problem to solve.</p></div><a class="button secondary" href="${prefix}contact.html">Let’s connect ${arrow}</a></section>`:''}</main>
<footer class="site-footer"><div class="container footer-inner"><p>© ${new Date().getUTCFullYear()} ${esc(profile.fullName)}</p><div class="footer-links"><a href="${esc(profile.github)}" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="${esc(profile.linkedin)}" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="mailto:${profile.email}">Email ↗</a></div></div></footer></body></html>`;
}

function projectCard(project,index,headingLevel=3) {
  return `<article class="project-card" data-category="${project.category}"><a class="project-art" href="projects/${project.slug}.html" aria-label="Explore ${esc(project.title)}"><div class="art-top"><span>${esc(project.eyebrow)}</span><span>PROJECT ${String(index+1).padStart(2,'0')}</span></div>${projectVisual(project.slug)}<span class="art-tag">${esc(project.metric.value)} · ${esc(project.metric.label)}</span></a><div class="project-meta">${eyebrow(project.categoryLabel)}<span class="small-mono">${String(index+1).padStart(2,'0')}</span></div><h${headingLevel}><a href="projects/${project.slug}.html">${esc(project.title)} <span aria-hidden="true">↗</span></a></h${headingLevel}><p>${esc(project.summary)}</p>${tags(project.tags)}</article>`;
}

const home = `<section class="hero" aria-labelledby="home-heading"><div class="hero-copy">${eyebrow('<span class="dot"></span> Machine Learning Engineer & Researcher')}<h1 id="home-heading">Turning complex<br>data into<br><span class="serif">meaningful impact.</span></h1><p class="intro"><strong>Hi, I’m ${esc(profile.shortName)}.</strong> I build machine learning systems and explore how AI can solve real-world problems. Currently studying Advanced Machine Learning with Professional Placement at the University of Bath.</p><div class="button-row"><a class="button" href="projects.html">Explore my work ${forward}</a>${resume()}</div><div class="hero-note"><svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M16 8c0 5-6 10-6 10S4 13 4 8a6 6 0 1 1 12 0Z" stroke="currentColor"/><circle cx="10" cy="8" r="2" stroke="currentColor"/></svg>Bath, United Kingdom <span aria-hidden="true">·</span> Open to ML & AI opportunities</div></div><div class="hero-visual"><div class="visual-topline"><span>THE SPACE BETWEEN DATA & POSSIBILITY</span><span>FIG. 01</span></div>${field()}<div class="hero-caption">Curiosity, translated into applied intelligence.</div><div class="visual-footer"><span>DATA</span><span>→ &nbsp; LEARNING &nbsp; →</span><span>IMPACT</span></div></div></section>
<div class="affiliation-strip" aria-label="Education and professional experience"><span class="affiliation-label">Learning & building<br>with</span><span class="affiliation"><span class="institution-mark" aria-hidden="true">▥</span><span>University of Bath<small>Advanced Machine Learning with Professional Placement</small></span></span><span class="affiliation"><span class="institution-mark" aria-hidden="true">S.</span><span>Spizen Technologies<small>Software Engineer (Machine Learning)</small></span></span><span class="affiliation"><span class="institution-mark" aria-hidden="true">◈</span><span>SRM University AP<small>BTech CSE AI &amp; ML</small></span></span><span class="affiliation"><span class="institution-mark" aria-hidden="true">⌘</span><span>IIT Roorkee<small>Virtual Labs</small></span></span></div>
<section class="section" aria-labelledby="selected-heading"><div class="section-heading"><div>${eyebrow('01 / Selected work')}<h2 id="selected-heading">Ideas, put into practice.</h2></div><a class="text-link" href="projects.html">View all projects ${arrow}</a></div><div class="project-grid">${projectCard(projects[0],0)}${projectCard(projects[3],3)}</div></section>
<section class="research-band" aria-labelledby="research-heading"><div>${eyebrow('02 / Research & Publications')}<h2 id="research-heading">Asking better questions.<br><em>Building deeper understanding.</em></h2><p>Applied machine learning research across energy systems, battery analytics, and intelligent classification.</p><a class="text-link" href="research.html">Explore my research ${arrow}</a></div><div class="research-highlight"><span class="number">${String(publications.length).padStart(2,'0')}</span><span class="number-label">Conference publications · 2025–2026</span><span class="small">LATEST PUBLICATION / ${esc(publications[0].shortConference)}</span><h3><a href="research.html#${esc(publications[0].id)}">${esc(publications[0].title)}</a></h3><span class="small">${esc(publications[0].venue)}</span></div></section>
<section class="home-about" aria-labelledby="home-about-heading"><div>${eyebrow('03 / A little about me')}<h2 id="home-about-heading">A researcher’s curiosity.<br>An engineer’s mindset.</h2></div><div><p>From real-time financial data at Spizen to smart grid research at SRM University AP, I’m interested in the point where rigorous experimentation becomes something useful.</p><p>Now at the University of Bath, I’m deepening that foundation in advanced machine learning.</p><a class="text-link" href="about.html">More about my journey ${arrow}</a></div></section>`;

const about = `<header class="page-intro">${eyebrow('About / The person behind the work')}<h1>Curious by nature.<br><span class="serif">An engineer by practice.</span></h1><p>I’m Shanmukha Krishna Chaitanya Munagala, also known as Shanmukha Munagala, a machine learning engineer and researcher based in Bath, United Kingdom.</p></header><div class="about-layout"><div class="about-prose">${profile.bio.map(p=>`<p>${esc(p)}</p>`).join('')}<div class="button-row">${resume()}<a class="text-link" href="experience.html">My experience ${arrow}</a></div></div><aside class="profile-note">${eyebrow('Always learning. Always building.')}<div class="profile-monogram" aria-hidden="true">Sm.</div><h2>From understanding data<br>to making it useful.</h2><p>Applied ML · Research · Engineering</p><p>Currently at the University of Bath, UK.</p></aside></div>
<section class="two-col-section" aria-labelledby="education-title"><div>${eyebrow('01 / Education')}<h2 id="education-title">A growing foundation.</h2></div><div>${education.map(item=>`<article class="education-item"><div class="small-mono">${esc(item.date)}</div><h3>${esc(item.degree)}</h3><p class="school">${esc(item.school)}</p><p>${esc(item.details)}</p><p>${esc(item.location)}</p></article>`).join('')}</div></section>
<section class="two-col-section" aria-labelledby="skills-title"><div>${eyebrow('02 / Technical toolkit')}<h2 id="skills-title">Tools for the question<br>at hand.</h2></div><div class="skills-grid">${skills.map(group=>`<div class="skill-group"><h3>${esc(group.title)}</h3><p>${group.items.map(esc).join(' · ')}</p></div>`).join('')}</div></section>
<section class="two-col-section" aria-labelledby="learning-title"><div>${eyebrow('03 / Continued learning')}<h2 id="learning-title">Beyond the curriculum.</h2></div><div>${certifications.map(cert=>`<article class="cert-item"><span class="cert-icon" aria-hidden="true">✧</span><div><h3>${esc(cert.title)}</h3><p>${esc(cert.issuer)}</p></div></article>`).join('')}<h3 style="margin-top:35px;font-size:17px">Workshops & seminars</h3><div class="workshop-list">${workshops.map(item=>`<p><strong>${esc(item.title)}</strong>${esc(item.issuer)} · ${esc(item.date)}</p>`).join('')}</div></div></section>`;

const experiencePage = `<header class="page-intro">${eyebrow('Experience / Learning through building')}<h1>From experimentation<br><span class="serif">to real-world systems.</span></h1><p>Industry engineering, applied research, and educational technology. Each experience has shaped how I approach a problem.</p></header><section class="timeline" aria-label="Professional experience">${experience.map(item=>`<article class="timeline-item"><div class="timeline-time"><span class="small-mono">${esc(item.date)}</span><p>${esc(item.location)}</p></div><div class="timeline-body"><h2>${esc(item.role)}</h2><p class="company">${esc(item.company)}</p><p style="font-size:14px;margin-bottom:20px">${esc(item.description)}</p><ul>${item.highlights.map(text=>`<li>${esc(text)}</li>`).join('')}</ul>${tags(item.tags)}</div></article>`).join('')}</section><div class="research-interests"><h2>What connects the work</h2><p>Careful data preparation, clear evaluation, and collaboration across disciplines. Whether working with financial transactions or grid parameters, I start with the problem the system needs to solve.</p></div>`;

const projectsPage = `<header class="page-intro">${eyebrow('Projects / Selected explorations')}<h1>Real data.<br><span class="serif">Useful possibilities.</span></h1><p>A collection of machine learning projects across energy, language, computer vision, and signal classification. Explore the problem, the approach, and the results.</p></header><div class="filters" role="group" aria-label="Filter projects by discipline"><button class="filter" data-filter="all" aria-pressed="true">All projects <span aria-hidden="true">04</span></button><button class="filter" data-filter="machine-learning" aria-pressed="false">Machine learning</button><button class="filter" data-filter="nlp" aria-pressed="false">NLP</button><button class="filter" data-filter="computer-vision" aria-pressed="false">Computer vision</button><span class="filter-status" id="filter-status" role="status" aria-live="polite">4 projects shown</span></div><noscript><p class="no-js-note">All projects are shown. Open any project to explore its case study.</p></noscript><div class="project-grid projects-page-grid">${projects.map((project,index)=>projectCard(project,index,2)).join('')}</div>`;

const researchPage = `<div class="research-intro"><header class="page-intro">${eyebrow('Research / Publications')}<h1>Better questions.<br><span class="serif">Deeper understanding.</span></h1><p>Exploring the application of machine learning to energy systems, battery health, and classification. A record of my conference publications and research interests.</p></header><aside class="research-stat"><span>04</span><p>Conference publications<br>2025–2026</p></aside></div><section class="publication-list" aria-label="Conference publications">${publications.map(pub=>`<article class="publication" id="${esc(pub.id)}"><span class="pub-year">${esc(pub.year)}</span><div><h2>${esc(pub.title)}</h2><p class="authors">${esc(pub.authors)}</p><p>${esc(pub.conference)} (${esc(pub.shortConference)})</p><p>${esc(pub.venue)} · ${esc(pub.date)}</p><p class="conference">${esc(pub.topic)}</p></div>${pub.doi?external(pub.doi,'Read paper','text-link pub-link'):`<span class="pub-label">${esc(pub.shortConference)}<br>CONFERENCE</span>`}</article>`).join('')}</section><section class="research-interests" aria-labelledby="interests-title"><h2 id="interests-title">Research interests</h2><p>${profile.interests.map(esc).join(' · ')}</p></section>`;

const contact = `<header class="page-intro">${eyebrow('Contact / Start a conversation')}<h1>Something interesting<br><span class="serif">in mind? Let’s talk.</span></h1><p>I’m interested in opportunities where I can contribute to thoughtful machine learning work, learn from others, and solve useful problems.</p></header><div class="contact-layout"><section aria-label="Contact details"><p class="contact-lead">For opportunities, research collaborations, or a good conversation about AI.</p><a class="email-link" href="mailto:${profile.email}">${profile.email}</a><div><button class="copy-button" data-copy-email="${profile.email}">Copy email ↗</button><p class="copy-status" id="copy-status" role="status" aria-live="polite"></p></div><a class="button" href="mailto:${profile.email}">Write an email ${arrow}</a><div class="contact-links"><a class="contact-link" href="${profile.linkedin}" target="_blank" rel="noopener noreferrer"><span>LinkedIn<small>Connect professionally</small></span>${arrow}</a><a class="contact-link" href="${profile.github}" target="_blank" rel="noopener noreferrer"><span>GitHub<small>Explore code and repositories</small></span>${arrow}</a><a class="contact-link" href="${esc(resumeRequestHref)}" data-resume-request="true"><span>Request Resume<small>Email me to request a copy</small></span>${arrow}</a></div></section><aside class="contact-aside"><div class="availability"><span class="dot"></span> Open to opportunities</div><h2>A good problem.<br>A thoughtful team.<br>A chance to contribute.</h2><p>I’m exploring roles and collaborations in:</p><ul><li>Machine Learning Engineering</li><li>Data Science</li><li>Applied AI & Research</li></ul><p class="location-note">Based in Bath, United Kingdom</p><p style="margin-top:14px;font-size:11px">MSc Advanced Machine Learning with Professional Placement<br>University of Bath · 2026–2028 (expected)</p></aside></div>`;

function casePage(project,index) {
  const next = projects[(index+1)%projects.length];
  return `<a class="back-link" href="../projects.html"><span aria-hidden="true">←</span> All projects</a><header class="page-intro case-intro">${eyebrow(`${esc(project.categoryLabel)} / ${esc(project.eyebrow)}`)}<h1>${esc(project.title)}</h1><p>${esc(project.summary)}</p></header><div class="project-art case-hero"><div class="art-top"><span>${esc(project.title)}</span></div>${projectVisual(project.slug)}<span class="art-tag">Conceptual illustration</span></div><div class="case-metrics" style="--metric-count:${project.results.length}">${project.results.map(result=>`<div class="case-metric"><strong>${esc(result.value)}</strong><p>${esc(result.label)}</p></div>`).join('')}</div><div class="case-content"><aside class="case-sidebar">${eyebrow('Tools & methods')}${tags(project.tags)}${project.repo?external(project.repo,'View source','text-link'):''}</aside><div class="case-main"><h2>The problem</h2><p>${esc(project.challenge)}</p><h2>The approach</h2>${project.approach.map((step,i)=>`<div class="approach-step"><span class="step-number">0${i+1}</span><div><h3>${esc(step.title)}</h3><p>${esc(step.description)}</p></div></div>`).join('')}<section class="outcome"><h2>What the work showed</h2><p>${esc(project.outcome)}</p></section><p class="case-note">${esc(project.limitations)}</p></div></div><a class="next-project" href="${next.slug}.html"><div>${eyebrow('Up next')}<h2>${esc(next.title)}</h2></div>${forward}</a>`;
}

const pages = [
 ['index.html','Machine Learning Engineer & Researcher','Shanmukha Munagala (Shanmukha Krishna Chaitanya Munagala), machine learning engineer and researcher. Explore AI projects, publications, and experience.','Home',home],
 ['about.html','About','Meet Shanmukha Krishna Chaitanya Munagala, also known as Shanmukha Munagala. Explore his education, skills, and machine learning research background.','About',about],
 ['experience.html','Experience','Machine learning engineering at Spizen Technologies, smart grid research at SRM University AP, and frontend development at IIT Roorkee.','Experience',experiencePage],
 ['projects.html','Projects','Explore machine learning case studies in smart grid stability, keyword extraction, waste image classification, and EEG seizure classification.','Projects',projectsPage],
 ['research.html','Research & Publications','Conference publications on battery degradation, smart grid faults, electric vehicle batteries, and fire and smoke classification.','Research',researchPage],
 ['contact.html','Contact','Connect with Shanmukha Krishna Chaitanya Munagala for machine learning, data science, applied AI, and research opportunities.','Contact',contact]
];
for (const [file,title,description,active,content] of pages) await writeFile(path.join(root,file), layout({title,description,active,content,file,cta:active!=='Contact'}));
await mkdir(path.join(root,'projects'),{recursive:true});
for (const [index,project] of projects.entries()) {
  const file = `projects/${project.slug}.html`;
  await writeFile(path.join(root,file),layout({title:project.title,description:project.summary,active:'Projects',content:casePage(project,index),prefix:'../',file,cta:false}));
}
await writeFile(path.join(root,'404.html'),layout({title:'Page not found',description:'This page could not be found. Return to Shanmukha Krishna Chaitanya Munagala’s portfolio.',active:'',file:'404.html',prefix:'/Portfolio/',cta:false,content:'<section class="not-found"><div class="eyebrow">A small detour</div><h1>404</h1><p>This page isn’t here. Let’s get you back to the portfolio.</p><a class="button" href="/Portfolio/index.html">Back to home →</a></section>'}));
await writeFile(path.join(root,'sitemap.xml'),sitemapXml([...pages.map(([file])=>file),...projects.map(project=>`projects/${project.slug}.html`)]));
console.log('Built 6 main pages, 4 project case studies, a 404 page, and the canonical sitemap.');
